# Copyright (c) 2020-2025 Caisse Nationale d’Assurance Maladie et Ministère de la Santé et de l’Accès aux Soins. All rights reserved.
# Use of this source code is governed by a CeCILL v2.1 license that can be
# found in the LICENSE file.

targets:
  $default:
    builders:
      mockito:mockBuilder:
        enabled: true
        generate_for:
          - test/mocks/mocks.dart
      ferry_generator|graphql_builder:
        enabled: true
        options:
          schema: fr_cnamts_ens|lib/graphql/ens/schema-ens.graphql
          when_extensions:
            when: true
            maybeWhen: true
          global_enum_fallbacks: true
          enum_fallbacks:
            MyEnumType: FERRY_UNKNOWN
      ferry_generator|serializer_builder:
        enabled: true
        options:
          schema: fr_cnamts_ens|lib/graphql/ens/schema-ens.graphql
