/*
  Copyright (c) 2020-2025 Caisse Nationale d’Assurance Maladie et Ministère de la Santé et de l’Accès aux Soins. All rights reserved.
  Use of this source code is governed by a CeCILL v2.1 license that can be found in the LICENSE file.
*/

import 'package:equatable/equatable.dart';

class EnsSendTrace extends Equatable {
  final EnsTraceType type;
  final Map<String, String>? params;

  const EnsSendTrace(this.type, {this.params});

  @override
  List<Object?> get props => [type, params];
}

enum EnsTraceType {
  CONSULT_RUBRIQUE_INFOS_CONNEXION,
  CONSULT_RUBRIQUE_CONFIDENTIALITE,
  CONSULT_RUBRIQUE_CONFIDENTIALITE_INFOS,
  CONSULT_RUBRIQUE_CLOTURE_PROFIL,
  CONSULT_RUBRIQUE_ACCES_PS,
  CONSULT_RUBRIQUE_ACCES_URGENCE,
  CONSULT_RUBRIQUE_BILAN_DE_PREVENTION,
  RETRAIT_STATUT_MEDECIN_ADMIN,
  CONSULT_RUBRIQUE_MESSAGERIE,
  CONSULT_MESSAGE,
  CONSULT_RUBRIQUE_PS,
  CONSULT_RUBRIQUE_SERVICES_SYNCHRO,
  CONSULT_RUBRIQUE_HISTORIQUE_ACTIVITE,
  CONSULT_RUBRIQUE_NOTIFS_MAILS,
  CONSULT_RUBRIQUE_HISTORIQUE_DONNEES,
  CONSULT_RUBRIQUE_TELECHARGEMENT_DONNEES,
  ATTRIBUTION_STATUT_MEDECIN_ADMIN,
  CONSULT_RUBRIQUE_MHS,
  CONSULT_RUBRIQUE_DOCUMENTS,
  CONSULT_DOC,
  TELECHARGEMENT_DOC,
  CONSULT_RUBRIQUE_VACCINATIONS,
  AJOUT_VACCINATION,
  SUPP_VACCINATION,
  CONSULT_RUBRIQUE_MALADIES,
  CONSULT_RUBRIQUE_TRAITEMENTS,
  CONSULT_RUBRIQUE_HOSPITALISATIONS,
  CONSULT_RUBRIQUE_HANDICAPS,
  CONSULT_RUBRIQUE_ALLERGIES,
  CONSULT_RUBRIQUE_ANTECEDENTS_FAMILIAUX,
  CONSULT_RUBRIQUE_HABITUDES_VIE,
  CONSULT_RUBRIQUE_MESURES,
  CONSULT_MESURE,
  CONSULT_RUBRIQUE_ENTOURAGE_VOLONTES,
  MODIF_MEMBRE_ENTOURAGE,
  SUPP_MEMBRE_ENTOURAGE,
  CONSULT_MENU_AGENDA,
  CONSULT_MENU_CATALOGUE_SERVICES,
  CONSULT_RUBRIQUE_HABITUDES_VIE_DETAIL,
  CONSULT_RUBRIQUE_ENTOURAGE,
  CONSULT_RUBRIQUE_DIRECTIVES_ANTICIPEES,
  CONSULT_RUBRIQUE_DON_ORGANE,
  CONSULT_RUBRIQUE_GROUPE_SANGUIN,
}
